name: phr_app
description: A PHR App using Flutter

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2
  qr_code_scanner: ^1.0.1
  provider: ^6.0.0
environment:
  sdk: '^3.5.0'
flutter:
  uses-material-design: true
